/* Generated by the build. A release is cached as one complete offline snapshot. */
const CACHE_NAME = "amaq-pwa-366e24be6e89f46f";
const ASSETS = [
  {
    "url": "/index.html"
  },
  {
    "url": "/style.css",
    "integrity": "sha256-2RydF1mOax7bs3QsrTXF/XT2WcWlJajj0hAxUXEtPNw="
  },
  {
    "url": "/mobile.css",
    "integrity": "sha256-VG8sLMljDGrZ3c3QDbORhBhn/x0Gx6nYNtKmAzhuvpQ="
  },
  {
    "url": "/expedition.css",
    "integrity": "sha256-VKJod4rJl1KRokh2GZiayzjPHmRMO8GJNjNQVNj9lVg="
  },
  {
    "url": "/ocean.bundle.js",
    "integrity": "sha256-2CZpzbcSgdJv/EoKeYLRJwRtk2XHQdCR1lwhjwS+9I0="
  },
  {
    "url": "/pwa.js",
    "integrity": "sha256-5IHDMVupBSUQgrH1M/Xmea11A2olAGaDLIyv03YsEBk="
  },
  {
    "url": "/manifest.webmanifest",
    "integrity": "sha256-98QtZ0jpcvOWAbh26nuodCpPDhlXnBud5z6dcpCEiso="
  },
  {
    "url": "/assets/materials/rock-color.jpg",
    "integrity": "sha256-ZE7nnff/v19q/DMLZN0/M3lLq4ggkV/mH/4MiOz9fs4="
  },
  {
    "url": "/assets/materials/rock-normal.jpg",
    "integrity": "sha256-pJjO9LphkfaVm20D+4NSY8dycZSCZKKJryRJercRHew="
  },
  {
    "url": "/assets/materials/rock-arm.jpg",
    "integrity": "sha256-GSEwOYHRK8z3LdKdio2vgj8dm7YEALRHxkdXIDweLa0="
  },
  {
    "url": "/assets/materials/sand-color.jpg",
    "integrity": "sha256-GAPX4oYbMEvqbS4STc1MZX/Lk4Q7hMF7stuYzkiofk4="
  },
  {
    "url": "/assets/materials/sand-normal.jpg",
    "integrity": "sha256-DzUYW3Il/iAniXu35FhsfesEiBdSTx7RBP2ufOgL3AY="
  },
  {
    "url": "/assets/materials/sand-arm.jpg",
    "integrity": "sha256-HcIfJgJG0OZRg209Rz4WamE3DQeEvPkeLaPnq3wCX50="
  },
  {
    "url": "/assets/models/reef-kit.glb",
    "integrity": "sha256-2vL9OqJqvaXLwH0osXf3Nb2BNWQsdSKw8KOboL8npQM="
  },
  {
    "url": "/icons/icon-192.png",
    "integrity": "sha256-vrszei2G6YXR0pnJEWorEX74faW5dtoP74QMOBIjYiI="
  },
  {
    "url": "/icons/icon-512.png",
    "integrity": "sha256-+EanyfMnMjXv6w1M7MfBlRuXKufTzb2Suqv6C11aVq0="
  },
  {
    "url": "/icons/maskable-512.png",
    "integrity": "sha256-+EanyfMnMjXv6w1M7MfBlRuXKufTzb2Suqv6C11aVq0="
  },
  {
    "url": "/icons/apple-touch-icon.png",
    "integrity": "sha256-hORAw+7sagN/1kBISqcYwYtLMbwjTOG77/D6NWvcnVQ="
  }
];
const PATHS = new Set(ASSETS.map(asset => asset.url));

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    try {
      // addAll is atomic. An interrupted download cannot replace a working release.
      await cache.addAll(ASSETS.map(asset => new Request(asset.url, {
        cache: 'reload', ...(asset.integrity ? { integrity: asset.integrity } : {})
      })));
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // Do not skipWaiting: a new release must not interrupt an active journey.
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith('amaq-pwa-') && key !== CACHE_NAME).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') event.waitUntil(self.skipWaiting());
  if (event.data?.type === 'CACHE_STATUS') event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    const entries = await Promise.all(ASSETS.map(asset => cache.match(asset.url)));
    event.ports[0]?.postMessage({ ready: entries.every(Boolean), release: CACHE_NAME });
  })());
});

self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  const isHome = event.request.mode === 'navigate' && (url.pathname === '/' || url.pathname === '/index.html');
  if (!isHome && !PATHS.has(url.pathname)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    const path = isHome ? '/index.html' : url.pathname;
    const cached = await cache.match(path);
    // Never mix fresh individual assets into an installed release's snapshot.
    return cached || fetch(event.request);
  })());
});
